-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 21:34:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pa2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pa2` ;

-- -----------------------------------------------------
-- Schema pa2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pa2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pa2` ;

-- -----------------------------------------------------
-- Table `pa2`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`Category` ;

CREATE TABLE IF NOT EXISTS `pa2`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(500) NULL DEFAULT NULL,
  `restaurant_id` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `restaurant_id_idx` (`restaurant_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pa2`.`Rating_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`Rating_details` ;

CREATE TABLE IF NOT EXISTS `pa2`.`Rating_details` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `review_count` INT NULL DEFAULT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pa2`.`Restaurant_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`Restaurant_details` ;

CREATE TABLE IF NOT EXISTS `pa2`.`Restaurant_details` (
  `details_id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(400) NULL DEFAULT NULL,
  `address` VARCHAR(300) NULL DEFAULT NULL,
  `phone_no` VARCHAR(45) NULL DEFAULT NULL,
  `estimated_price` VARCHAR(45) NULL DEFAULT NULL,
  `yelp_url` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`details_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pa2`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `pa2`.`Restaurant` (
  `restaurant_id` VARCHAR(50) NOT NULL DEFAULT '0',
  `restaurant_name` VARCHAR(450) NULL DEFAULT NULL,
  `details_id` INT NULL DEFAULT NULL,
  `rating_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`restaurant_id`),
  INDEX `details_id_idx` (`details_id` ASC) VISIBLE,
  INDEX `ratings_id_idx` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `details_id`
    FOREIGN KEY (`details_id`)
    REFERENCES `pa2`.`Restaurant_details` (`details_id`),
  CONSTRAINT `ratings_id`
    FOREIGN KEY (`rating_id`)
    REFERENCES `pa2`.`Rating_details` (`rating_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pa2`.`RestaurantCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`RestaurantCategories` ;

CREATE TABLE IF NOT EXISTS `pa2`.`RestaurantCategories` (
  `category_id` INT NOT NULL DEFAULT '0',
  `restaurant_id` VARCHAR(350) NOT NULL DEFAULT '0',
  INDEX `restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `pa2`.`Category` (`category_id`),
  CONSTRAINT `restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `pa2`.`Restaurant` (`restaurant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pa2`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pa2`.`Students` ;

CREATE TABLE IF NOT EXISTS `pa2`.`Students` (
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
